urls.py
from django.conf.urls.defaults import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()



#from django.conf import settings
#if settings.DEBUG:
#    urlpatterns += patterns('',
#        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
#    )

wze/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()
from django.conf import settings


urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'wze.views.home', name='home'),
    # url(r'^wze/', include('wze.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^load/$', 'apps.mod.views.load', name="load"),
    url(r'^save/(?P<format>\w*|\\)$', 'apps.mod.views.save', name='save'),
    url(r'^tables/$', 'apps.mod.views.table_info', name='tables'),
    url(r'^researches/$', 'apps.mod.views.researches', name='researches'),
    url(r'^research_tree/$', 'apps.mod.views.save_graviz_tree'),
    url(r'^data_mining/$', 'apps.mod.views.data_mining'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include(admin.site.urls)),
)
if settings.DEBUG:
   from django.views.static import serve
   _media_url = settings.MEDIA_URL
   if _media_url.startswith('/'):
       _media_url = _media_url[1:]
       urlpatterns += patterns('',
        (r'^%s(?P<path>.*)$' % _media_url,
        serve,
        {'document_root': settings.MEDIA_ROOT}))
   del(_media_url, serve)

apps/research/models.py
from apps.admin.fields import (WZCharField, WZNameField, WZPieField, WZPositiveIntegerField,
                               WZForeignKey, WZUnusedField, WZIconField)
from apps.admin.model import WZModel
from apps.structure.models import Structure
from apps.function.models import Function
import os
from django.conf import settings
from django.contrib import admin


class WZResearchModel(WZModel):
    class Meta:
        abstract = True

    @classmethod
    def load(cls):
        if os.path.exists(os.path.join(settings.PATH_TO_MOD, cls.FILE_PATH)):
            super(WZResearchModel, cls).load()
        else:
            cls.objects.all().delete()
            if cls in admin.site._registry:
                admin.site.unregister(cls)


TECH_CHOICE = ((0, 'Major'),(1, 'Minor'))


COMPONENT_TYPE = [(x,x) for x in ('WEAPON', 'BODY', 'REPAIR', 'PROPULSION', 'SENSOR', 'CONSTRUCT', 'ECM')] + [('0', 'None')]
def get_component_link(key, comp_type):
    return '/admin/{0}/{0}/{1}'.format(comp_type.lower(), key)


class Research(WZResearchModel):
    '''determines a wide variety of stats for individual research topics, such as price, time-to-research, icon to use for representation, etc. For more information about this, go here.'''
    FILE_PATH = 'stats/research/%s/research.txt'
    load_from_first = True

    key = WZNameField()
    unused1 = WZUnusedField()
    subgroup_icon = WZIconField()
    major_tech = WZPositiveIntegerField(choices=TECH_CHOICE, help_text='Affects whether or not "Major research completed" is played, and whether or not it appears in Intelligence.')
    main_icon = WZIconField()
    imd = WZPieField(help_text='IMD to display for tech')
    imd2 = WZUnusedField()
    msg_name = WZCharField(help_text='Message in Intelligence screen for tech; must be zero for minor techs') # load messages
    structure_name = WZCharField(blank=True, help_text='if non-zero, use this for research graphics') # 0 or foreing key
    comp_name = WZCharField(help_text='if non-zero, use this for research graphics')
    comp_type = WZCharField(help_text='if previous was non-zero, indicate what type of component its')
    research_points = WZPositiveIntegerField(help_text='Points cost to research it (price = points/32, capped at 450)')
    key_topic = WZPositiveIntegerField(help_text='Is it a key topic? Visual effect only.')
    unused2 = WZUnusedField()
    unused3 = WZUnusedField()
    unused4 = WZUnusedField()
    unused5 = WZUnusedField()
    unused6 = WZUnusedField()
    unused7 = WZUnusedField()
    unused8 = WZUnusedField()
    class Meta:
        abstract = True

class Research_Cam1(Research):
    FILE_PATH = Research.FILE_PATH % ('cam1')
    class Meta:
        verbose_name = 'Research (camapain 1)'
        verbose_name_plural = 'Researchs (camapain 1)'
class Research_Cam2(Research):
    FILE_PATH = Research.FILE_PATH % ('cam2')
    class Meta:
        verbose_name = 'Research (camapain 2)'
        verbose_name_plural = 'Researchs (camapain 2)'
class Research_Cam3(Research):
    FILE_PATH = Research.FILE_PATH % ('cam3')
    class Meta:
        verbose_name = 'Research (camapain 3)'
        verbose_name_plural = 'Researchs (camapain 3)'

class Research_Multiplayer(Research):
    FILE_PATH = Research.FILE_PATH % ('multiplayer')
    load_from_first = False
    class Meta:
        verbose_name = 'Research (multiplayer)'
        verbose_name_plural = 'Researches (multiplayer)'



    
class ResearchPreRequisites(WZResearchModel):
    '''determines the prerequisites of research objects.'''
    FILE_PATH = 'stats/research/%s/prresearch.txt'
    load_from_first = True
    class Meta:
        abstract = True

    def __unicode__(self):
        return '%s requaire %s' % (self.research, self.pre_requisites)

class ResearchPreRequisites_Cam1(ResearchPreRequisites):
    FILE_PATH = ResearchPreRequisites.FILE_PATH % ('cam1')
    research = WZForeignKey(Research_Cam1)
    pre_requisites = WZForeignKey(Research_Cam1, related_name='pre_requisites')
    unused1 = WZUnusedField()


class ResearchPreRequisites_Cam2(ResearchPreRequisites):
    FILE_PATH = ResearchPreRequisites.FILE_PATH % ('cam2')
    research = WZForeignKey(Research_Cam2)
    pre_requisites = WZForeignKey(Research_Cam2, related_name='pre_requisites')
    unused1 = WZUnusedField()


class ResearchPreRequisites_Cam3(ResearchPreRequisites):
    FILE_PATH = ResearchPreRequisites.FILE_PATH % ('cam3')
    research = WZForeignKey(Research_Cam3)
    pre_requisites = WZForeignKey(Research_Cam3, related_name='pre_requisites')
    unused1 = WZUnusedField()


class ResearchPreRequisites_Multiplayer(ResearchPreRequisites):
    FILE_PATH = ResearchPreRequisites.FILE_PATH % ('multiplayer')
    research = WZForeignKey(Research_Multiplayer)
    pre_requisites = WZForeignKey(Research_Multiplayer, related_name='pre_requisites')
    unused1 = WZUnusedField()
    
    
class ResultStructure(WZResearchModel):
    ''' determines which structures are made available upon researching the selected item.'''
    FILE_PATH = 'stats/research/%s/resultstructure.txt'
    class Meta:
        abstract = True

    def __unicode__(self):
        return '%s for %s' % (self.structure, self.research)

class ResultStructure_Cam1(ResultStructure):
    FILE_PATH = ResultStructure.FILE_PATH % ('cam1')
    research = WZForeignKey(Research_Cam1)
    structure = WZForeignKey(Structure)
    unused1 = WZUnusedField()
    unused2 = WZUnusedField()


class ResultStructure_Cam2(ResultStructure):
    FILE_PATH = ResultStructure.FILE_PATH % ('cam2')
    research = WZForeignKey(Research_Cam2)
    structure = WZForeignKey(Structure)
    unused1 = WZUnusedField()
    unused2 = WZUnusedField()


class ResultStructure_Cam3(ResultStructure):
    FILE_PATH = ResultStructure.FILE_PATH % ('cam3')
    research = WZForeignKey(Research_Cam3)
    structure = WZForeignKey(Structure)
    unused1 = WZUnusedField()
    unused2 = WZUnusedField()


class ResultStructure_Multiplayer(ResultStructure):
    FILE_PATH = ResultStructure.FILE_PATH % ('multiplayer')
    research = WZForeignKey(Research_Multiplayer)
    structure = WZForeignKey(Structure)
    unused1 = WZUnusedField()
    unused2 = WZUnusedField()



class ResearchFunctions(WZResearchModel):
    '''determines which upgrades to apply upon researching the selected item.'''
    load_from_first = True
    FILE_PATH = 'stats/research/%s/researchfunctions.txt'

    class Meta:
        abstract = True

    def get_funct_link(self):
        return get_component_link(self.function.key, 'function')

class ResearchFunctions_Cam1(ResearchFunctions):
    FILE_PATH = ResearchFunctions.FILE_PATH % ('cam1')
    research = WZForeignKey(Research_Cam1)
    function = WZForeignKey(Function)
    unused = WZUnusedField()


class ResearchFunctions_Cam2(ResearchFunctions):
    FILE_PATH = ResearchFunctions.FILE_PATH % ('cam2')
    research = WZForeignKey(Research_Cam2)
    function = WZForeignKey(Function)
    unused = WZUnusedField()


class ResearchFunctions_Cam3(ResearchFunctions):
    FILE_PATH = ResearchFunctions.FILE_PATH % 'cam3'
    research = WZForeignKey(Research_Cam3)
    function = WZForeignKey(Function)
    unused = WZUnusedField()


class ResearchFunctions_Multiplayer(ResearchFunctions):
    FILE_PATH = ResearchFunctions.FILE_PATH % ('multiplayer')
    research = WZForeignKey(Research_Multiplayer)
    function = WZForeignKey(Function)
    unused = WZUnusedField()


class ResearchStructure(WZResearchModel):
    '''presumably, this determines which structures are required in order for the research item to become available. (For example, you'll need an HQ in order to be able to research a whole bunch of defenses.)'''
    load_from_first = True
    FILE_PATH = 'stats/research/%s/researchstruct.txt'

    class Meta:
        abstract = True

    def __unicode__(self):
        return '%s allow %s' % (self.research, self.structure)

    def get_structure_link(self):
        return get_component_link(self.structure.key, 'structure')

class ResearchStructure_Cam1(ResearchStructure):
    FILE_PATH = ResearchStructure.FILE_PATH % ('cam1')
    research = WZForeignKey(Research_Cam1)
    structure = WZForeignKey(Structure)
    unused = WZUnusedField()


class ResearchStructure_Cam2(ResearchStructure):
    FILE_PATH = ResearchStructure.FILE_PATH % ('cam2')
    research = WZForeignKey(Research_Cam2)
    structure = WZForeignKey(Structure)
    unused = WZUnusedField()


class ResearchStructure_Cam3(ResearchStructure):
    FILE_PATH = ResearchStructure.FILE_PATH % ('cam3')
    research = WZForeignKey(Research_Cam3)
    structure = WZForeignKey(Structure)
    unused = WZUnusedField()


class ResearchStructure_Multiplayer(ResearchStructure):
    FILE_PATH = ResearchStructure.FILE_PATH % ('Multiplayer')
    research = WZForeignKey(Research_Multiplayer)
    structure = WZForeignKey(Structure)
    unused = WZUnusedField()



class ResultComponent(WZResearchModel):
    ''' determines which components are made available upon researching the selected item.'''
    FILE_PATH = 'stats/research/%s/resultcomponent.txt'
    load_from_first = True

    class Meta:
        abstract = True

    def __unicode__(self):
        return '%s replaces %s(%s) for %s(%s)' % (self.research, self.component, self.type, self.replaced_component, self.replaced_type)

    def get_component_link(self):
        return get_component_link(self.component, self.type)

class ResultComponent_Cam1(ResultComponent):
    FILE_PATH = ResultComponent.FILE_PATH % ('cam1')
    research = WZForeignKey(Research_Cam1)
    component = WZCharField(help_text='Name for component')
    type = WZCharField(choices=COMPONENT_TYPE)
    replaced_component = WZCharField(help_text='Name for component')

templates/data_mining.html
{% extends "admin/base_site.html" %}

{% if not is_popup %}
    {% block breadcrumbs %}
        <div class="breadcrumbs">
            <a href="/">Home</a>
            &rsaquo; <a href=".">Save</a>
        </div>
    {% endblock %}
{% endif %}

{% block content %}
    {% for name, blob in blobs %}
            <h2>{{ name }}</h2>
            {%  for item in blob %}
                <div> {{ item }}</div>
            {% endfor %}
    {% endfor %}
{% endblock %}

templates/researches.html
{% for research in researches %}
<ul id='{{ research.key }}'>
    <b>{{ research }}</b>
    <ul>
    <li><label>Cost: </label>{{ research.research_points }}</li>
    {% if research.pre_requisites.count or research.researchstructure_set.count%}
        <label>Pre_Requisites: </label>
            <ul>
            {% for pre in research.pre_requisites.all %}
            <li><a href="#{{ pre.research.key }}">{{ pre.research }}</a></li>
            {% endfor %}
            {% for comp in research.researchstructure_set.all %}
                <li><a href="{{ comp.get_structure_link }}">{{ comp.structure }}</a></li>
            {% endfor %}
            </ul>
        {% endif %}



        {% if research.researchcomponent_set.count or research.researchfunctions_set.count or research.resultstructure_set.count%}
            <label>Added: </label>
            <ul>
                {% for comp in research.researchcomponent_set.all  %}
                    <li><a href="{{ comp.get_component_link }}">{{ comp.component }}</a></li>
                {% endfor %}

                {% for funct in research.researchfunctions_set.all %}
                    <li><a href="{{ funct.get_funct_link }}">{{ funct.function }}</a></li>
                {% endfor %}

                {% for comp in research.resultstructure_set.all %}
                    <li><a href="{{ comp.get_structure_link }}">{{ comp.structure }}</a></li>
                {% endfor %}
            </ul>
        {% endif %}


        {% if research.researchobsoletecomponent_set.count or research.researchobsoletstructure_set.count %}
            <label>Obsolete: </label>
            <ul>
                {% for comp in research.researchobsoletecomponent_set.all %}
                    <li><a href="{{ comp.get_component_link }}">{{ comp.component }}</a></li>
                {% endfor %}
            </ul>
                {% for comp in research.researchobsoletstructure_set.all  %}
                    <li><a href="{{ comp.get_structure_link }}">{{ comp.structure }}</a></li>
                {% endfor %}
        {% endif %}



        </ul>
</ul>
{% endfor %}

templates/save.html
{% extends "admin/base_site.html" %}

{% if not is_popup %}
    {% block breadcrumbs %}
        <div class="breadcrumbs">
            <a href="/">Home</a>
            &rsaquo; <a href=".">Save</a>
        </div>
    {% endblock %}
{% endif %}

{% block content %}<div id="content-main">
    {% for file, lines in diff %}
        {% if lines %}
            <h2>{{ file }}</h2>
            {%  for color, text in lines %}
                <div style="color:{{color}}; white-space:nowrap;">{{ text }}</div>
            {% endfor %}
        {% endif %}
    {% endfor %}
{% endblock %}

templates/table_info.html
{% extends "admin/base_site.html" %}

{% if not is_popup %}
    {% block breadcrumbs %}
        <div class="breadcrumbs">
            <a href="/">Home</a>
            &rsaquo; <a href=".">Tables</a>
        </div>
    {% endblock %}
{% endif %}

{% block content %}<div id="content-main">

    <ul id='begin' style='text-align:left; right:0px; position: absolute; font-size: 80%;'>
        {% for table in tables %}
            <li><h3><a href="#{{ table.get_class_name }}">{{ table.get_class_name }}</a></h3>
        {% endfor %}
    </ul>

    <table style="width: 80%">
        {% for table in tables %}
            {#    <caption>{{ table.get_class_name }}</caption>#}
            <tr><th colspan="4" id='{{ table.get_class_name }}'><h3 align="left">{{ table.get_class_name }}
                <a href="#begin">&uarr;</a>
            </h3></th></tr>


            <tr>
                <th>Name</th>
                <th>Type</th>
                <th>Limits</th>
                <th>Default</th>
                <th>Description</th>
            </tr>
            {% for fields in table.get_template %}
                <tr>
                    {% for field in fields.get_data %}
                        <td>
                            {{ field|safe}}
                        </td>
                    {% endfor %}
                </tr>
            {% endfor %}
        {% endfor %}

    </table>
{% endblock %}